"""add device code model

Revision ID: 51b73f5e9b83
Revises: 834b1a697901
Create Date: 2025-01-08 11:46:44.396752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b73f5e9b83'
down_revision = '834b1a697901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_code', sa.String(length=64), nullable=False),
    sa.Column('user_code', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_code_device_code'), ['device_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_device_code_user_code'), ['user_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_code_user_code'))
        batch_op.drop_index(batch_op.f('ix_device_code_device_code'))

    op.drop_table('device_code')
    # ### end Alembic commands ###
