"""add oauth models

Revision ID: f4cf4ed1a92c
Revises: 51b73f5e9b83
Create Date: 2025-01-23 17:08:03.459977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4cf4ed1a92c'
down_revision = '51b73f5e9b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('client_secret', sa.String(length=64), nullable=False),
    sa.Column('redirect_uri', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('authorization_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('redirect_uri', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('authorization_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authorization_code_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authorization_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authorization_code_code'))

    op.drop_table('authorization_code')
    op.drop_table('client')
    # ### end Alembic commands ###
